### ISSUE TITLE
Plugin has been renamed

### ISSUE THREAD

**Issue by brunoban** [binxio/blog-how-to-automate-google-site-verification-with-terraform#1]
Hello, just a heads up that this plugin changed names and it's not well documented in the plugin itself (best resource I could find was your blog post, thanks for that btw). 

It mainly changed the data structure for the dns_token. It changed from `google-site-verifier_dns_token` to `googlesiteverification_dns_token`. 

I'll add a PR if I have the time.

Thanks again!

**Comment by mvanholsteijn** [comment]
Thanks for the feedback! I fixed the blog, in this repository the proper resource name is used.
